### ISSUE TITLE
mdcheck presubmit is now broken

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/healthcare-data-protection-suite#33]
Example: https://pantheon.corp.google.com/cloud-build/builds/9af7ca0a-18b8-48ff-a942-0625baf9cf00;step=0?project=hcls-data-protection-internal

Throws this error:
```
/usr/local/bin/markdownlint -> /usr/local/lib/node_modules/markdownlint-cli/markdownlint.js
+ markdownlint-cli@0.23.0
added 36 packages from 28 contributors in 2.261s
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:799
      throw error;
      ^

TypeError: content.trimEnd is not a function
    at handleRunEnd (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:38:27)
    at MD037.forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:133:13)
    at forMetadata (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:256:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:254:16)
    at Object.MD037 [as function] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:71:5)
    at forRule (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:593:20)
    at Array.forEach (<anonymous>)
    at lintContent (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:639:14)
    at lintContentWrapper (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:679:12)
```

A new version of markdownlint-cli was released recently, 0.23.0 on May 5, 1:00am EDT (2020-05-05T04:52:03.666Z). This version is possibly broken.

Suggest to pin it to 0.22.0 for now.

**Comment by MartinPetkov** [comment]
Opened https://github.com/igorshubovych/markdownlint-cli/issues/90 for that library.
